version: 2.1

commands:
  mac_install_python:
    parameters:
      python_version:
        description: "version of python to install"
        type: string
        default: 3.7.10
    steps:
      - run: |
          brew update
          python --version
          sudo -H pip install --upgrade virtualenv
          brew install pyenv
          echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
          echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
          source ~/.bash_profile
          pyenv install --list
          pyenv install << parameters.python_version >>
          pyenv versions
          pyenv global << parameters.python_version >>
          python --version

  install_run_tests:
    steps:
      - run: |
          python setup.py install
          python -m pip install pytest
      - run: pytest
        
jobs:
  mac_python_3_7:
    shell: /bin/bash --login
    macos:
      xcode: '10.3.0'
    steps:
    - checkout
    - mac_install_python:
        python_version: "3.7.10"
    - install_run_tests


  mac_python_3_8:
    shell: /bin/bash --login
    macos:
      xcode: '10.3.0'
    steps:
    - checkout
    - mac_install_python:
        python_version: "3.8.10"
    - install_run_tests

  mac_python_3_9:
    shell: /bin/bash --login
    macos:
      xcode: '10.3.0'
    steps:
    - checkout
    - mac_install_python:
        python_version: "3.9.5"
    - install_run_tests

  mac_python_3_10:
    shell: /bin/bash --login
    macos:
      xcode: '10.3.0'
    steps:
    - checkout
    - mac_install_python:
        python_version: "3.10.0b1"
    - install_run_tests

  linux_python_3_7:
    docker:
      - image: python:3.7
    steps:
    - checkout
    - install_run_tests

  linux_python_3_8:
    docker:
      - image: python:3.8
    steps:
    - checkout
    - install_run_tests

  linux_python_3_9:
    docker:
      - image: python:3.9
    steps:
    - checkout
    - install_run_tests

  linux_python_3_10:
    docker:
      - image: python:3.10
    steps:
    - checkout
    - install_run_tests

workflows:
  version: 2
  python_matrix_build:
    jobs:
      - mac_python_3_7
      - mac_python_3_8
      - mac_python_3_9
      - mac_python_3_10
      - linux_python_3_7
      - linux_python_3_8
      - linux_python_3_9
      - linux_python_3_10
